version: '3.9'
services:
  db:
    image: mysql:8.0.29
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: Europe/Lisbon
      MYSQL_ROOT_PASSWORD: robert
      MYSQL_USER: robert
      MYSQL_PASSWORD: robert
      MYSQL_DATABASE: test1
    ports:
      - 3308:3308
    expose:
      - 3308
    networks:
      - my-network
  test1:
    image: robertgleison12/api-v2
    restart: always
    build: .
    working_dir: /api-2.0
    environment:
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3308/test1
      SPRING.DATASOURCE.USERNAME: robert
      SPRING.DATASOURCE.PASSWORD: robert
      TZ: Europe/Lisbon
    ports:
      - 8081:80
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - my-network

networks:
  my-network:
    driver: bridge